name: harvest_tracker
description: Harvest Map Tracker.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_auth: ^0.15.2  
  flutter_secure_storage: ^3.3.1+1 
  googleapis: ^0.54.0  
  googleapis_auth: ^0.2.11 
  google_maps_flutter: ^0.5.27+1
  google_sign_in: ^4.1.0  
  uuid: ^2.0.4
  localstorage: ^3.0.2+5
  shared_preferences: ^0.5.8
  json_annotation: ^3.0.1
  flutter_local_notifications: ^1.4.4+1
  flutter_email_sender: ^3.0.1
  workmanager: ^0.2.2
  rxdart: ^0.24.1
  path_provider: ^1.5.1  
  url_launcher: ^5.4.11
  geolocator: ^5.3.2+2
  location: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  build_runner: ^1.10.0
  json_serializable: ^3.3.0

flutter:
  assets:
    - assets/

  uses-material-design: true
